# Generated by Django 2.2.16 on 2022-01-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220108_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписчики', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
