# Generated by Django 2.2.16 on 2022-01-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20220121_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user_ip',
            new_name='user',
        ),
    ]
